show databases;
USE WWE;

DROP TABLE POPULARIDADE;

CREATE TABLE POPULARIDADE(
SUPERSTAR VARCHAR(20) NULL,
FINANCE DOUBLE NULL,
PPVs VARCHAR(50),
EVENTS VARCHAR(50),
DATES DATE NULL,
FOREIGN KEY (LUTADORES) REFERENCES LUTADORES (SUPERSTARS)
);
SELECT * FROM POPULARIDADE;